addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

env:
  global:
    - PROJECT="HelpScout"
    - VERSION="0.1.0"
    - RELEASE="0.0.2"
    - secure: "Capq94JRU+jt5V4vnEyeFvJmotXSsYCn0y8ViSG3m1uxeJLxVS4idi2N0vB7XJuaix9iIKu6FTAFmhyFFRnDJgMmfGIGiKQOcJb6ksMwCGuVYl9zOI1pht43M+fuLbw5BZksgTbQPCgmOt0xWqgQBkc3KCXztF4LHZg7D8n4hDaBZ61/Ax63Tg4GTAPOUVMUl4q/SH2dwQcB4snJJ1aKaa3keubcd7jL/lC9aIZxrZGFrwlpzlhPu0r69BVYJrxgEKiokKIKAV20vQuUEHLeLz+eQg0wLbckbPV9NkjITBKxYYSo3ChWR8UmUXrP/qwNJ3qCTZxs/gxaeGYuwcftJxgVCcP+XfCdqClHTKLInMP/jeXH7IrAhYZtCGOdk4rhspiwcCkEO22Kdk+t74pbbs+M+SwZMk4T2/8B1NDs0Tnz5MF63Qz/tT7/zDk+e37ZeZ6iwwa4/4ALjPja3uLxix4S3Tl90Eu57PJkfXjEdkxRRAvvZbbKvOOOMc23UmJ8FPua2ZnbD1tz8OrIpxGFQ9HdFycIUHkF3rB1ruH/iu2WZnrtn6TQ8vSaWgifW/bfFqod0Z620ttVHFGljkJ4cMfO5ornLdHRYMXSU54FfnErnEKRdHPNRnbU7XZeK2tVEl9W7906VRWkvPIANJK850Moqj8pZ7LeYcChW/2oXTA="
  matrix:
    - TESTS="1"
    - LINT="1"
    - PYPI="1"
    - DOCS="1"

install:
  - git clone --depth=1 https://github.com/LasLabs/python-quality-tools.git ${HOME}/python-quality-tools
  - export PATH=${HOME}/python-quality-tools/travis:${PATH}
  - travis_install

script:
  - travis_run

after_success:
  - travis_after_success
